### ISSUE TITLE
Bug i think...

### ISSUE THREAD

**Issue by LambrosYT** [kicjow/CrazyEnvoy#1]
14.12 13:16:12 [Server] ERROR Could not pass event PlayerInteractEvent to CrazyEnvoy v1.1 14.12 13:16:12 [Server] INFO org.bukkit.event.EventException 14.12 13:16:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 13:16:12 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 13:16:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 13:16:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 13:16:12 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 13:16:12 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 13:16:12 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 13:16:12 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 13:16:12 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 13:16:12 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 13:16:12 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111] 14.12 13:16:12 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111] 14.12 13:16:12 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 13:16:12 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 13:16:12 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 13:16:12 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 13:16:12 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 13:16:12 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111] 14.12 13:16:12 [Server] INFO Caused by: java.lang.NullPointerException 14.12 13:16:12 [Server] INFO at me.BadBones69.envoy.Methods.makeItem(Methods.java:136) ~[?:?] 14.12 13:16:12 [Server] INFO at me.BadBones69.envoy.api.Flare.getFlare(Flare.java:19) ~[?:?] 14.12 13:16:12 [Server] INFO at me.BadBones69.envoy.api.Flare.isFlare(Flare.java:23) ~[?:?] 14.12 13:16:12 [Server] INFO at me.BadBones69.envoy.controlers.FlareControl.onFlareActivate(FlareControl.java:23) ~[?:?] 14.12 13:16:12 [Server] INFO at sun.reflect.GeneratedMethodAccessor472.invoke(Unknown Source) ~[?:?] 14.12 13:16:12 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111] 14.12 13:16:12 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111] 14.12 13:16:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 13:16:12 [Server] INFO ... 17 more

**Comment by kicjow** [comment]
Hello, this is a config error. You are missing this option in the config.yml.
https://github.com/kicjow/CrazyEnvoy/blob/master/Config.yml#L19

**Comment by LambrosYT** [comment]
thanks kicjow now its ok!
