### ISSUE TITLE
Error again...

### ISSUE THREAD

**Issue by LambrosYT** [kicjow/CrazyEnvoy#2]
14.12 18:51:49 [Server] INFO LambrosYT issued server command: /envoy flare 1 LambrosYT 14.12 18:51:49 [Server] FATAL Error executing task 14.12 18:51:49 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NullPointerException 14.12 18:51:49 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_111] 14.12 18:51:49 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_111] 14.12 18:51:49 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:45) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 18:51:49 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 18:51:49 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 18:51:49 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 18:51:49 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 18:51:49 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111] 14.12 18:51:49 [Server] INFO Caused by: java.lang.NullPointerException 14.12 18:51:49 [Server] INFO at me.dadus33.chatitem.filters.Log4jFilter.checkMessage(Log4jFilter.java:83) ~[?:?] 14.12 18:51:49 [Server] INFO at me.dadus33.chatitem.filters.Log4jFilter.filter(Log4jFilter.java:58) ~[?:?] 14.12 18:51:49 [Server] INFO at org.apache.logging.log4j.core.filter.CompositeFilter.filter(CompositeFilter.java:231) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 18:51:49 [Server] INFO at org.apache.logging.log4j.core.filter.AbstractFilterable.isFiltered(AbstractFilterable.java:124) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 18:51:49 [Server] INFO at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:400) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 18:51:49 [Server] INFO at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 18:51:49 [Server] INFO at org.apache.logging.log4j.core.Logger.log(Logger.java:110) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 18:51:49 [Server] INFO at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:609) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 18:51:49 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.util.ForwardLogHandler.publish(ForwardLogHandler.java:33) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 18:51:49 [Server] INFO at java.util.logging.Logger.log(Logger.java:738) ~[?:1.8.0_111] 14.12 18:51:49 [Server] INFO at java.util.logging.Logger.doLog(Logger.java:765) ~[?:1.8.0_111] 14.12 18:51:49 [Server] INFO at java.util.logging.Logger.log(Logger.java:876) ~[?:1.8.0_111] 14.12 18:51:49 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1168) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 18:51:49 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 18:51:49 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 18:51:49 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 18:51:49 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 14.12 18:51:49 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]

**Comment by LambrosYT** [comment]
sr for ticket spam 👍

**Comment by kicjow** [comment]
That error is not from my plugin. It is from your Item Chat plugin.
